### ISSUE TITLE
LunaCore Setup wird nicht angezeigt

### ISSUE THREAD

**Issue by byKeksYT** [leonhausdorf/LunaCore#3]
Ich habe ein Problem mit dem Nutzen von LunaCore.
Ich habe es auf meinem Server installiert, der PHP 8.0 nutzt, und wenn ich auf die index.php navigiere, wird mir eine 404-Seite angezeigt. Wenn ich versuche, das Setup aufzurufen, wird mir einfach eine weiße Seite angezeigt, auf der nichts steht. 
Würde die Dokumentation funktionieren, würde ich mich zuerst dort erkundigen, jedoch ist dies zum aktuellen Zeitpunkt nicht der Fall.

Woran kann das liegen?

**Comment by byKeksYT** [comment]
Hallo @leonhausdorf ,

auch wenn ich `https://verstandlxs.eu/lunacore/setup` eingebe, wird mir eine 404-Seite angezeigt. In der `routes.json` steht drin, dass /setup auf die Setup-Seite weiterleiten sollte.

Hier ein Screenshot zur Erläuterung:
https://verstandlxs.de/screens/35defb505821a610ba010bf45c6a39f3.png

**Comment by leonhausdorf** [comment]
Issue mit 1.4.4 behoben
